export const DISCOVERY_TILE_RADIUS_METERS = 850;
export const DISCOVERY_TILE_SPACING_METERS = 650;
export const DISCOVERY_MAX_TILES_PER_JOB = 240;
export const DISCOVERY_MAX_RETRIEVAL_PASSES_PER_TILE = 5;
export const DISCOVERY_MAX_DETAIL_ENRICHMENTS_PER_JOB = 300;
export const DISCOVERY_MAX_FINAL_RESULTS_PER_JOB = 1_000;
export const DISCOVERY_MAX_NEARBY_RESULTS_PER_TILE = 20;
export const DISCOVERY_COORDINATE_DEDUPE_THRESHOLD_METERS = 55;
